#
# Required Gitlab CI/CD Variables:
#
# - CI_REGISTRY: e.g. docker-registry.joelpet.se
# - CI_REGISTRY_IMAGE: e.g. docker-registry.joelpet.se/ab-svenska-pass-in-firejail
# - CI_REGISTRY_USER: <registry-user>
# - CI_REGISTRY_PASSWORD: <registry-password>
# - DOCKER_AUTH_CONFIG: See https://docs.gitlab.com/ee/ci/docker/using_docker_images.html#define-an-image-from-a-private-container-registry
#
image: $CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA

build:
  stage: build
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  script:
    # See https://docs.gitlab.com/ee/ci/docker/using_docker_images.html#configuring-a-job
    - echo "{\"auths\":{\"$CI_REGISTRY\":{\"username\":\"$CI_REGISTRY_USER\",\"password\":\"$CI_REGISTRY_PASSWORD\"}}}" > /kaniko/.docker/config.json
    - >
      /kaniko/executor
      --context $CI_PROJECT_DIR
      --dockerfile $CI_PROJECT_DIR/docker/Dockerfile
      --destination $CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA

shellcheck:
  stage: test
  script:
    - make shellcheck
